// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giolkgofcpwfcddudprb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdpb2xrZ29mY3B3ZmNkZHVkcHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODY3MjMsImV4cCI6MjA2NDc2MjcyM30.Rh8yB8fYDeNOOL2ET-Jd7deAqSwbAQCSCQoFV_CIq8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);